apiVersion: v1
kind: Pod 
metadata: 
  name: client-pod
spec:
  containers:
  - name: curl
    image: appropriate/curl
    command: ["/bin/sh"]
    args: ["-c","while true; do curl --fail --silent --show-error test-service:4000; sleep 30; done"]
